FROM node:22-alpine3.21
WORKDIR /app
COPY package*.json ./
RUN npm install
# RUN apk update && apk install stress --yes
COPY . .
RUN npm run compile
HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=1 CMD [ "curl", "-f", "http://localhost:3000/health" ]
CMD ["npm", "start"]
EXPOSE 3000